select * from tabela_de_clientes, tabela_de_produtos;

SELECT 
    nf.cpf, 
    YEAR(nf.data_venda) AS ano, 
    SUM(inf.quantidade) AS volume_total
FROM notas_fiscais nf
INNER JOIN itens_notas_fiscais inf 
    ON nf.numero = inf.numero
GROUP BY 
    nf.cpf, 
    YEAR(nf.data_venda);
    
    
    
    SELECT 
    NF.CPF, 
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS ANO_MES, 
    SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF 
    ON NF.NUMERO = INF.NUMERO
GROUP BY 
    NF.CPF, ANO_MES;
    
    

-- Selecionar os campos, formatar a data e somar a quantidade
SELECT 
    NF.CPF, 
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS ANO_MES, 
    SUM(INF.QUANTIDADE) AS QNTD_VENDAS
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF 
    ON NF.NUMERO = INF.NUMERO
GROUP BY 
    NF.CPF, 
    ANO_MES;
    
    
    
    
    
    -- Agrupar e Somar a quantidade
SELECT 
    NF.CPF, TC.NOME AS NOME
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS ANO_MES, 
    SUM(INF.QUANTIDADE) AS QNTD_VENDAS
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF 
    ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes AS TC
ON TC.CPF = NF.CPF
GROUP BY 

    NF.CPF, 
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');


/*Obter o limite de volume total de compra 
por cliente*/

SELECT * FROM TABELA_DE_CLIENTES AS TC;

SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA
FROM TABELA_DE_CLIENTES AS TC;



SELECT 
    TC.CPF, 
    TC.NOME, 
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS ANO_MES, 
    SUM(INF.QUANTIDADE) AS QNTD_VENDAS, 
    MAX(TC.VOLUME_DE_COMPRA) AS QNTD_LIMITE
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF 
    ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES AS TC 
    ON TC.CPF = NF.CPF
GROUP BY 
    TC.CPF, 
    TC.NOME, 
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');


SELECT 
    TC.CPF, 
    TC.NOME, 
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS ANO_MES, 
    SUM(INF.QUANTIDADE) AS QNTD_VENDAS, 
    MAX(TC.VOLUME_DE_COMPRA) AS QNTD_LIMITE
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF 
    ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES AS TC 
    ON TC.CPF = NF.CPF
GROUP BY 
    TC.CPF, 
    TC.NOME, 
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m');
    SELECT X.CPF, X.NOME, X.ANO_MES, X.QNTD_VENDAS, X.QNTD_LIMITE,
    ABS(X.QNTD_LIMITE - X.QNTD_VENDAS) AS DIFERENCA,
    CASE
    WHEN (X.QNTD_LIMITE - X.QNTD_VENDAS) <0
    THEN "VOLUME EXCIDO"
    ELSE "VOLUME ADEQUADO"
  END AS STATUS_VENDA
  FROM(
SELECT 
    TC.CPF, 
    TC.NOME, 
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS ANO_MES, 
    SUM(INF.QUANTIDADE) AS QNTD_VENDAS, 
    MAX(TC.VOLUME_DE_COMPRA) AS QNTD_LIMITE
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF 
    ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES AS TC 
    ON TC.CPF = NF.CPF
GROUP BY 
    TC.CPF, 
    TC.NOME, 
    DATE_FORMAT(NF.DATA_VENDA, '%Y-%m'))AS X;



