SELECT 
    TP.SABOR,
    YEAR(NF.DATA_VENDA) AS ANO,
    SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL,
    ROUND(
        (SUM(INF.QUANTIDADE) / 
        (SELECT SUM(INF2.QUANTIDADE)
         FROM itens_notas_fiscais INF2
         INNER JOIN notas_fiscais NF2 
            ON NF2.NUMERO = INF2.NUMERO
         WHERE YEAR(NF2.DATA_VENDA) = 2016)
        ) * 100, 2
    ) AS PERCENTUAL
FROM itens_notas_fiscais INF
INNER JOIN notas_fiscais NF 
    ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_produtos TP 
    ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY QUANTIDADE_TOTAL DESC;